name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v2
    - name: Static config
      run: rustup target add x86_64-unknown-linux-musl
    - name: Install 
      run: cargo install --features=ssl --target x86_64-unknown-linux-musl --verbose websocat 
    - name: Info 
      run: which websocat 
