name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: centos:centos6 

    steps:
    - uses: actions/checkout@v2
    - name: Install 
      run: cargo install --features=ssl --verbose websocat 
    - name: Info 
      run: which websocat 
